source "https://rubygems.org"
gem "neography"
gem "neo4j-core", :git => "git://github.com/andreasronge/neo4j-core", :tag => "v3.0.0.alpha.10"
gem "sinatra"
gem "thin"
gem "sinatra-contrib"
gem "erubis"
